version: "3"

volumes:
  postgres-vol:

services:
  zebra:
    build: ./
    restart: always
    volumes:
      - ${LocationItemImage}:${LocationItemDocker}
    ports:
      - 4000:4000
      - 8080:8080
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=zebradb sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zebradb
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./scripts/drop.sql:/docker-entrypoint-initdb.d/1-drop.sql
      - ./scripts/populate.sql:/docker-entrypoint-initdb.d/1-populate.sql